// Page Builder Engine - File Extraction from Components

import type { ComponentSpec, GeneratedFile, GenerationOptions } from "@/types/page-builder"

export function extractFilesFromComponents(
  components: ComponentSpec[], 
  options?: GenerationOptions
): GeneratedFile[] {
  const files: GeneratedFile[] = []
  const processedPaths = new Set<string>()

  for (const component of components) {
    extractComponentFiles(component, files, processedPaths, options)
  }

  // Add supporting files
  if (options?.includeTests) {
    files.push(...generateTestFiles(components))
  }

  if (options?.includeStorybook) {
    files.push(...generateStorybookFiles(components))
  }

  return files
}

function extractComponentFiles(
  component: ComponentSpec,
  files: GeneratedFile[],
  processedPaths: Set<string>,
  options?: GenerationOptions,
  basePath = "src/components/generated"
): void {
  // Determine file path
  const fileName = toKebabCase(component.name)
  const extension = component.code?.includes("use client") ? "tsx" : "tsx"
  const relativePath = `${basePath}/${fileName}.${extension}`
  
  if (processedPaths.has(relativePath)) return
  processedPaths.add(relativePath)

  // Generate the file content
  const content = generateComponentFile(component)
  
  files.push({
    path: relativePath,
    content,
    language: "tsx",
  })

  // Process children recursively
  if (component.children) {
    for (const child of component.children) {
      extractComponentFiles(child, files, processedPaths, options, basePath)
    }
  }
}

function generateComponentFile(component: ComponentSpec): string {
  const lines: string[] = []

  // File header comment
  lines.push(`// Generated by Silas Studio Page Builder`)
  lines.push(`// Component: ${component.name} (${component.type})`)
  lines.push(`// Description: ${component.description}`)
  lines.push(`// Timestamp: ${new Date().toISOString()}`)
  lines.push("")

  // Imports
  if (component.imports.length > 0) {
    for (const imp of component.imports) {
      const importStr = formatImport(imp)
      if (importStr) lines.push(importStr)
    }
    lines.push("")
  }

  // Component code
  if (component.code) {
    lines.push(component.code)
  } else {
    // Generate from spec if no code provided
    lines.push(generateComponentFromSpec(component))
  }

  // Children exports (if composite component)
  if (component.children && component.children.length > 0) {
    lines.push("")
    lines.push("// Sub-components")
    for (const child of component.children) {
      lines.push(`export { ${child.name} } from "./${toKebabCase(child.name)}"`)
    }
  }

  return lines.join("\n")
}

function formatImport(imp: { source: string; imports: string[]; type: "default" | "named" | "namespace" }): string {
  const { source, imports, type } = imp
  
  if (type === "default") {
    return `import ${imports[0]} from "${source}"`
  }
  
  if (type === "namespace") {
    return `import * as ${imports[0]} from "${source}"`
  }
  
  // Named imports
  const importList = imports.map(i => i.includes(" as ") ? i : i).join(", ")
  return `import { ${importList} } from "${source}"`
}

function generateComponentFromSpec(component: ComponentSpec): string {
  const propDestructuring = component.props
    .map(p => p.name)
    .join(", ")
  
  const defaultProps = component.props
    .filter(p => p.defaultValue !== undefined)
    .map(p => `${p.name}: ${p.defaultValue}`)
    .join(", ")

  const className = component.styling.container ? `className={cn("${component.styling.container}", className)}` : "className={cn(className)}"
  
  return `interface ${component.name}Props {
${component.props.map(p => `  ${p.name}${p.required ? "" : "?"}: ${p.type}${p.description ? ` // ${p.description}` : ""}`).join("\n")}
}

export function ${component.name}({ ${propDestructuring} }: ${component.name}Props) {
  return (
    <div ${className}>
      {/* ${component.description} */}
      {${propDestructuring.includes("children") ? "children" : `/* TODO: Implement ${component.name} */`}}
    </div>
  )
}

${defaultProps ? `${component.name}.defaultProps = { ${defaultProps} }` : ""}`
}

function toKebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase()
}

function generateTestFiles(components: ComponentSpec[]): GeneratedFile[] {
  return components.map(comp => ({
    path: `src/components/generated/${toKebabCase(comp.name)}.test.tsx`,
    content: generateTestFile(comp),
    language: "tsx" as const,
  }))
}

function generateTestFile(component: ComponentSpec): string {
  return `// Generated test for ${component.name}
import { render, screen } from "@testing-library/react"
import { ${component.name} } from "./${toKebabCase(component.name)}"

describe("${component.name}", () => {
  it("renders without crashing", () => {
    render(<${component.name} />)
    expect(screen.getByText("${component.description}")).toBeInTheDocument()
  })
})`
}

function generateStorybookFiles(components: ComponentSpec[]): GeneratedFile[] {
  return components.map(comp => ({
    path: `src/components/generated/${toKebabCase(comp.name)}.stories.tsx`,
    content: generateStorybookFile(comp),
    language: "tsx" as const,
  }))
}

function generateStorybookFile(component: ComponentSpec): string {
  return `// Generated Storybook story for ${component.name}
import type { Meta, StoryObj } from "@storybook/react"
import { ${component.name} } from "./${toKebabCase(component.name)}"

const meta: Meta<typeof ${component.name}> = {
  title: "Generated/${component.name}",
  component: ${component.name},
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
}

export default meta
type Story = StoryObj<typeof ${component.name}>

export const Default: Story = {
  args: {
    ${component.props.filter(p => p.required).map(p => `${p.name}: "${p.type}"`).join(",\n    ")}
  },
}`
}